name: CI
on: 
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci   # similar to npm install but more suitable for ci enviroments
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      # On push, once the pull request is approved
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain dramatic-app.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}